spring:
  application:
    name: PruebaPase
  datasource:
    url: jdbc:postgresql://db:5432/pruebaBase
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      initialization-fail-timeout: 60000
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect